### ISSUE TITLE
installing kaleidoscope hides photo editing node groups that are not used ...

### ISSUE THREAD

**Issue by ArtSmash** [blenderskool/kaleidoscope#22]
Photo editing nodes no longer show in the node groups menu after installing this add on and after restarting kaleidoscope node groups do not show either. Using Blender 2.78c. Also, the sketch node group affects all nodes not just the ones in the stream it was placed in which is not like the behavior of any of the other photo editing nodes.

**Comment by blenderskool** [comment]
Kaleidoscope add-on is custom nodes for Materials.
Photo Editing Nodes are node groups for Compositor.
Hence, both are in separate node editors.

Also, the Sketch node modifies nearly the entire image. So mostly, the changes made on it would be really less effective because of completely (or nearly) black color.
![](http://i.imgur.com/6WY8dW8.gif)

**Comment by ArtSmash** [comment]
Ok, thank you.
